### ISSUE TITLE
Ambiguous response on error requests

### ISSUE THREAD

**Issue by Jayk5** [nuance-communications/mix-cli#182]
Whenever any mix command generates an error, the request completion message still displays it as done which can be confusing.
e.g. -
```
$ mix projects:list -O 9999 
 ›   Error: Organization not found.
 ›   Code: ENOTFOUND
 ›   Try this: verify the values passed to the command flags.
Retrieving projects for organization ID 9999... done
```

```
$ mix app-configs:deploy -C 9999
 ›   Error: ApplicationConfig with id=9999 does not exist.
 ›   Code: ENOTFOUND
 ›   Try this: verify the values passed to the command flags.\
Deploying application configuration... done
```

```
$ mix entities:list -P 9999999999999999999999999999
 ›   Error: Invalid project id provided
 ›   Code: EINVALIDVALUE
 ›   Try this: verify the values passed to the command flags.
Retrieving entities for project ID 1e+28... done
```

This can be fixed by adding `CliUx.ux.action.stop(chalk.red('Aborted'))` in the handleError() function in mix-command.ts.

**Comment by grof** [comment]
Let's use the word "Failed" instead of "Aborted".

Rationale:

- In the UI, when we ask users for confirmation, we tell them they can abort the operation by doing ctrl-c. So "abort" carries a sense that it was user-initiated. "Failed" will more clearly communicate that it's the system which is stopping the requested operation.
